# Generated by Django 5.0 on 2024-01-30 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_mailing_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('set_is_activated', 'Может отключать рассылку')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
        migrations.RemoveField(
            model_name='client',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='client',
            name='name',
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='is_active',
        ),
        migrations.AddField(
            model_name='client',
            name='full_name',
            field=models.CharField(default=1, max_length=50, verbose_name='ФИО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailing',
            name='is_activated',
            field=models.BooleanField(default=True, verbose_name='активная рассылка'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='periodicity',
            field=models.CharField(choices=[('разовая', 'разовая'), ('ежедневно', 'ежедневно'), ('раз в неделю', 'раз в неделю'), ('раз в месяц', 'раз в месяц')], default='разовая', max_length=50, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('Создана', 'Создана'), ('Запущена', 'Запущена'), ('Завершена', 'Завершена')], help_text='Выберите Создана или Завершена', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Тема'),
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_mailing_time', models.DateTimeField(auto_now=True, verbose_name='время последней рассылки')),
                ('status', models.CharField(max_length=50, null=True, verbose_name='статус попытки')),
                ('mailing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailings.mailing', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'logs',
            },
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
