# Generated by Django 5.0 on 2024-02-05 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_alter_mailing_options_remove_client_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='body',
        ),
        migrations.RemoveField(
            model_name='message',
            name='mailing',
        ),
    ]
